/*
 * Buffet Config Manager
 *
 * A configuration service that stores and retrieves configuration.
 *
 * API version: 0.1.0
 * Contact: apiteam@swagger.io
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package api

import (
	"net/http"

	// "github.com/getsentry/sentry-go"
	"github.com/gin-gonic/gin"

	"github.com/aeekayy/stilla/pkg/api/models"
	"github.com/aeekayy/stilla/pkg/utils"
)

// AddConfig - Create a new configuration and configuration value
func AddConfig(dal *DAL) gin.HandlerFunc {
	fn := func(c *gin.Context) {
		var req models.ConfigIn

		if err := c.ShouldBind(&req); err != nil {
			dal.Logger.Errorf("unable to parse request: %v", err)
			c.JSON(http.StatusBadRequest, gin.H{"error": "unable to insert configuration"})
			return
		}

		// span := sentry.StartSpan(c, "config.insert")
		configID, err := dal.InsertConfig(c, req, c.Request)
		// span.Finish()

		if err != nil {
			output := utils.SanitizeLogMessage(req.ConfigName, req.ConfigName)
			dal.Logger.Errorf("unable to insert config: %v", output)
			c.JSON(http.StatusBadRequest, gin.H{"error": "unable to insert configuration"})
			return
		}

		dal.Logger.Infof("created config object %s", configID)
		c.JSON(http.StatusCreated, gin.H{
			"data": configID,
		})
	}

	return fn
}

// GetConfigByID - Retrieve a configuration by configuration ID
func GetConfigByID(dal *DAL) gin.HandlerFunc {
	fn := func(c *gin.Context) {
		configID := c.Param("configId")
		hostID := c.Param("hostId")

		if configID == "" {
			dal.Logger.Errorf("unable to parse request")
			c.JSON(http.StatusBadRequest, gin.H{"error": "unable to retrieve configuration"})
			return
		}

		// span := sentry.StartSpan(c, "config.get")
		config, err := dal.GetConfig(c, configID, hostID, c.Request)
		// span.Finish()

		if err != nil {
			output := utils.SanitizeLogMessage(configID, configID)
			dal.Logger.Errorf("unable to retrieve config: %v", output)
			c.JSON(http.StatusBadRequest, gin.H{"error": "unable to retrieve configuration"})
			return
		}

		dal.Logger.Infof("retrieved config")
		c.JSON(http.StatusOK, gin.H{
			"data": config,
		})
	}

	return fn
}

// GetConfigs - Get a paginated list of configurations
func GetConfigs(dal *DAL) gin.HandlerFunc {
	fn := func(c *gin.Context) {
		offset := c.Query("offset")
		limit := c.Query("limit")

		// span := sentry.StartSpan(c, "config.get_all")
		configs, err := dal.GetConfigs(c, offset, limit, c.Request)
		// span.Finish()

		if err != nil {
			dal.Logger.Errorf("unable to retrieve configurations: %v", err)
			c.JSON(http.StatusBadRequest, gin.H{"error": "unable to retrieve configurations"})
			return
		}

		c.JSON(http.StatusOK, gin.H{
			"data": configs,
		})
	}

	return gin.HandlerFunc(fn)
}

// UpdateConfigByID - Update a configuration by configuration ID
func UpdateConfigByID(dal *DAL) gin.HandlerFunc {
	fn := func(c *gin.Context) {
		configID := c.Param("configId")
		var req models.UpdateConfigIn

		if configID == "" {
			dal.Logger.Errorf("unable to parse request")
			c.JSON(http.StatusBadRequest, gin.H{"error": "unable to update configuration"})
			return
		}

		if err := c.ShouldBind(&req); err != nil {
			dal.Logger.Errorf("unable to parse request: %v", err)
			c.JSON(http.StatusBadRequest, gin.H{"error": "unable to update configuration"})
			return
		}

		// span := sentry.StartSpan(c, "config.update")
		config, err := dal.UpdateConfigByID(c, configID, req, c.Request)
		// span.Finish()

		if err != nil {
			dal.Logger.Errorf("unable to retrieve config: %v", err)
			c.JSON(http.StatusBadRequest, gin.H{"error": "unable to retrieve configuration"})
			return
		}

		dal.Logger.Infof("retrieved config")
		c.JSON(http.StatusOK, gin.H{
			"data": config,
		})
	}

	return fn
}
