/*
 * Buffet Config Manager
 *
 * A configuration service that stores and retrieves configuration.
 *
 * API version: 0.1.0
 * Contact: apiteam@swagger.io
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package api

import (
	"context"
	"net/http"

	"github.com/gin-gonic/gin"
)

// GetRecords - Retrieves an audit log entry
func GetRecords(dal *DAL) gin.HandlerFunc {
	fn := func(c *gin.Context) {
		offset := c.Query("offset")
		limit := c.Query("limit")

		logs, err := dal.GetAuditLogs(context.TODO(), offset, limit, c.Request)

		if err != nil {
			dal.Logger.Errorf("unable to retrieve audit logs: %v", err)
			c.JSON(http.StatusBadRequest, gin.H{"error": "unable to retrieve audit logs"})
			return
		}

		c.JSON(http.StatusOK, gin.H{
			"data": logs,
		})
	}

	return gin.HandlerFunc(fn)
}
