/*
 * Buffet Config Manager
 *
 * A configuration service that stores and retrieves configuration.
 *
 * API version: 0.1.0
 * Contact: apiteam@swagger.io
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

import (
	"time"

	"go.mongodb.org/mongo-driver/bson/primitive"
)

// ConfigStore ...
type ConfigStore struct {
	Created       time.Time            `json:"created,omitempty",bson:"created,omitempty"`
	Modified      time.Time            `json:"modified,omitempty",bson:"modified"`
	ConfigVersion ConfigVersion        `json:"config_version",bson:"config_version"`
	ConfigName    string               `json:"config_name",bson:"config_name"`
	Owner         string               `json:"owner",bson:"owner"`
	Parents       []primitive.ObjectID `json:"parents,omitempty",bson:"parents,omitempty"`
	ID            primitive.ObjectID   `json:"id,omitempty",bson:"_id"`
}
