/*
 * Buffet Config Manager
 *
 * A configuration service that stores and retrieves configuration.
 *
 * API version: 0.1.0
 * Contact: apiteam@swagger.io
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

import (
	"time"

	"go.mongodb.org/mongo-driver/bson/primitive"
)

// ConfigVersion ...
type ConfigVersion struct {
	ID         primitive.ObjectID `json:"id,omitempty",bson:"_id,omitempty"`
	Config     map[string]string  `json:"config,omitempty",bson:"config,omitempty"`
	ConfigName string             `json:"config_name,omitempty",bson:"config_name,omitempty"`
	Checksum   [32]byte           `form:"checksum" json:"checksum" yaml:"checksum"`
	CreatedBy  string             `json:"created_by,omitempty",bson:"created_by,omitempty"`
	Created    time.Time          `json:"created,omitempty",bson:"created"`
}
