/*
 * Buffet Config Manager
 *
 * A configuration service that stores and retrieves configuration.
 *
 * API version: 0.1.0
 * Contact: apiteam@swagger.io
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

// ConfigIn ...
type ConfigIn struct {

	// Unique name for the configuration
	ConfigName string                 `json:"config_name"`
	Owner      string                 `json:"owner"`
	Config     map[string]interface{} `json:"config,omitempty"`
	Host       string                 `json:"host,omitempty"`
	Parents    []string               `json:"parents,omitempty"`
	Tags       []string               `form:"tags" json:"tags" yaml:"tags"`
}
