---
images:
- name: postgres
  image: postgres:15
  ports:
  - 5432:5432
  env:
  - POSTGRES_PASSWORD: postgres
- name: redis
  image: redis:7
  ports: 
  - 6379:6379
- name: zookeeper
  image: bitnami/zookeeper
  ports:
  - 2181:2181
  env:
  - ALLOW_ANONYMOUS_LOGIN: yes
- name: kafka
  image: bitnami/kafka:3
  ports:
  - 9092:9092
  env:
  - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE: true
  - ALLOW_PLAINTEXT_LISTENER: yes
  - KAFKA_CFG_ZOOKEEPER_CONNECT: stilla-bitnami-zookeeper:2181
-  name: mongo
   image: mongo:6
   ports:
    - 27017:27017
   env:
   - MONGO_INITDB_ROOT_USERNAME: mongo
   - MONGO_INITDB_ROOT_PASSWORD: mongo